[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "VITE_TMDB_API_KEY,VITE_TMDB_BASE_URL,VITE_TMDB_IMAGE_BASE_URL"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200